# Análise de Consumo de Produtos em Cidades

Uma empresa de pesquisa de mercado está analisando o consumo de três produtos (A, B e C) em quatro cidades diferentes. Os dados coletados incluem o número de unidades vendidas e o preço médio de cada produto em cada cidade. Além disso, a empresa quer considerar o impacto de três fatores econômicos (índice de emprego, renda média e índice de confiança do consumidor) em cada cidade.

## Dados

### Matriz de vendas (unidades vendidas):
- **Cidade 1**: [100, 150, 200]
- **Cidade 2**: [120, 130, 160]
- **Cidade 3**: [80, 100, 180]
- **Cidade 4**: [90, 120, 140]

### Matriz de preços (em $):
- **Cidade 1**: [10, 15, 20]
- **Cidade 2**: [12, 14, 18]
- **Cidade 3**: [11, 13, 19]
- **Cidade 4**: [9, 16, 17]

### Matriz de fatores econômicos (normalizada):
- **Cidade 1**: [0.8, 0.7, 0.9]
- **Cidade 2**: [0.7, 0.8, 0.75]
- **Cidade 3**: [0.6, 0.6, 0.8]
- **Cidade 4**: [0.75, 0.7, 0.85]

## Tarefas

a) Calcule a receita total para cada cidade.  
b) Determine o produto escalar entre a receita da Cidade 1 e os fatores econômicos da Cidade 2.  
c) Calcule a matriz de correlação entre as vendas dos produtos.  
d) Verifique se os vetores de venda da Cidade 1 e Cidade 2 são linearmente independentes.  
e) Encontre uma combinação linear dos fatores econômicos da Cidade 1 que melhor se aproxime dos fatores da Cidade 4.  
f) Calcule o rank da matriz de vendas.

## Análise Matricial Abrangente

Este código resolve todas as tarefas propostas no enunciado. Vou explicar brevemente cada parte:

- **a)** Calcula a receita total multiplicando as matrizes de vendas e preços elemento a elemento e somando os resultados para cada cidade.
- **b)** Realiza o produto escalar entre o vetor de receita da Cidade 1 e o vetor de fatores econômicos da Cidade 2.
- **c)** Calcula a matriz de correlação entre as vendas dos produtos usando a função `np.corrcoef()`.
- **d)** Verifica se os vetores de venda da Cidade 1 e Cidade 2 são linearmente independentes calculando o rank da matriz formada por esses vetores.
- **e)** Encontra uma combinação linear dos fatores econômicos da Cidade 1 que melhor se aproxima dos fatores da Cidade 4 usando otimização numérica.
- **f)** Calcula o rank da matriz de vendas usando `np.linalg.matrix_rank()`.


In [24]:
import numpy as np
from scipy import stats
from scipy.optimize import minimize

# Dados
vendas = np.array([
    [100, 150, 200],
    [120, 130, 160],
    [80, 100, 180],
    [90, 120, 140]
])

precos = np.array([
    [10, 15, 20],
    [12, 14, 18],
    [11, 13, 19],
    [9, 16, 17]
])

fatores_economicos = np.array([
    [0.8, 0.7, 0.9],
    [0.7, 0.8, 0.75],
    [0.6, 0.6, 0.8],
    [0.75, 0.7, 0.85]
])

# a) Calcule a receita total para cada cidade

receita = np.sum(vendas * precos, axis=1)
print("a) Receita total por cidade:")
print(receita)

# b) Produto escalar entre a receita da Cidade 1 e os fatores econômicos da Cidade 2
produto_escalar = np.dot(vendas[0] * precos[0], fatores_economicos[1])
print("\nb) Produto escalar:")
print(produto_escalar)

# c) Matriz de correlação entre as vendas dos produtos
correlacao = np.corrcoef(vendas.T)
print("\nc) Matriz de correlação das vendas:")
print(correlacao)

# d) Verificar independência linear entre vetores de venda da Cidade 1 e Cidade 2
# np.linalg.matrix_rank retorna o rank da matriz, que é o número de vetores linearmente independentes
def sao_linearmente_independentes(v1, v2):
    matriz = np.column_stack((v1, v2))
    return np.linalg.matrix_rank(matriz) == 2

independentes = sao_linearmente_independentes(vendas[0], vendas[1])
print("\nd) Vetores de venda da Cidade 1 e Cidade 2 são linearmente independentes:")
print(independentes)


# e) Combinação linear dos fatores econômicos
def erro_combinacao(coefs, v1, v2, v3, v4):
    return np.sum((coefs[0]*v1 + coefs[1]*v2 + coefs[2]*v3 - v4)**2)

v1, v2, v3 = fatores_economicos[0]
v4 = fatores_economicos[3]

resultado = minimize(erro_combinacao, [1, 1, 1], args=(v1, v2, v3, v4))
print("\ne) Coeficientes da combinação linear:")
print(resultado.x)

# f) Rank da matriz de vendas
rank = np.linalg.matrix_rank(vendas)
print("\nf) Rank da matriz de vendas:")
print(rank)

a) Receita total por cidade:
[7250 6140 5600 5110]

b) Produto escalar:
5500.0

c) Matriz de correlação das vendas:
[[ 1.          0.6094494  -0.07559289]
 [ 0.6094494   1.          0.3721042 ]
 [-0.07559289  0.3721042   1.        ]]

d) Vetores de venda da Cidade 1 e Cidade 2 são linearmente independentes:
True

e) Coeficientes da combinação linear:
[0.32646048 0.41065293 0.24226803]

f) Rank da matriz de vendas:
3


In [17]:
import numpy as np

# Definindo os vetores nutricionais
banana = np.array([420, 27, 1.3])
maca = np.array([200, 25, 0.5])
baca = np.array([310, 26, 0.9])

print("Vetores nutricionais:")
print(f"Banana: {banana}")
print(f"Maçã: {maca}")
print(f"Baça: {baca}")

# a) Verificar se maçãs e bananas são linearmente independentes
#Se eu receber 3 vetores, np.linalg.matrix_rank deveria retornar 3 para serem linearmente independentes
def sao_linearmente_independentes(v1, v2):
    matriz = np.column_stack((v1, v2))
    return np.linalg.matrix_rank(matriz) == 2

independentes = sao_linearmente_independentes(banana, maca)
print("\na) Bananas e maçãs são linearmente dependetes (representam a mesma coisa porém com valores diferentes multiplicados por um escalar)?")
if (independentes):
    print("Não")
else:
    print("Sim, Não")

# # Calculando o determinante para demonstrar
# matriz_bm = np.column_stack((banana, maca))
# det = np.linalg.det(matriz_bm[:2, :2])  # Usando apenas as duas primeiras linhas
# print(f"Determinante da matriz 2x2: {det}")

# b) Verificar se baça traz mais variedade nutricional
def combinar_linearmente(v1, v2, v_alvo):
    A = np.column_stack((v1, v2))
    return np.linalg.lstsq(A, v_alvo, rcond=None)[0]

coeficientes = combinar_linearmente(banana, maca, baca)
erro = np.linalg.norm(banana * coeficientes[0] + maca * coeficientes[1] - baca)

print("\nb) Baça traz mais variedade nutricional?")
print(f"Coeficientes da combinação linear: {coeficientes}")
print(f"Erro da aproximação: {erro}")

if erro > 1e-10:  # Considerando um pequeno erro de arredondamento
    print("Resposta: Sim, baça traz mais variedade nutricional.")
else:
    print("Resposta: Não, baça não traz mais variedade nutricional.")

Vetores nutricionais:
Banana: [420.   27.    1.3]
Maçã: [200.   25.    0.5]
Baça: [310.   26.    0.9]

a) Bananas e maçãs são linearmente dependetes (representam a mesma coisa porém com valores diferentes multiplicados por um escalar)?
Não

b) Baça traz mais variedade nutricional?
Coeficientes da combinação linear: [0.5 0.5]
Erro da aproximação: 1.1390953157792155e-13
Resposta: Não, baça não traz mais variedade nutricional.
