# Questão de Manipulação e Operações Matriciais

## Enunciado:

Você está analisando dados sobre as vendas de três produtos em uma loja durante três meses. Os dados são representados por três matrizes:

### Matriz A (Vendas):
Cada linha representa as vendas de um produto em três meses.

\[ 
A = 
\begin{bmatrix}
20 & 30 & 40 \\
15 & 25 & 35 \\
25 & 35 & 45 
\end{bmatrix} 
\]

### Matriz B (Preços):
Cada linha representa o preço de cada produto nos três meses.

\[ 
B = 
\begin{bmatrix}
5 & 6 & 7 \\
4 & 5 & 6 \\
6 & 7 & 8 
\end{bmatrix} 
\]

### Matriz D (Descontos):
Cada linha representa o desconto aplicado a cada produto em cada mês.

\[ 
D = 
\begin{bmatrix}
1 & 1 & 2 \\
0 & 2 & 1 \\
2 & 1 & 0 
\end{bmatrix} 
\]

### Questões:

1.  Calcule a matriz de receita total (Matriz C), onde cada elemento \( C_{ij} \) é obtido multiplicando as vendas pelo preço correspondente.

2.  Aplique os descontos da Matriz D na Matriz C e calcule a matriz de receita final (Matriz E).

3.  Verifique se as vendas do primeiro produto podem ser expressas como uma combinação linear das vendas dos outros produtos.

4.  Calcule a média das receitas totais para cada mês e determine qual mês teve a maior média de receita.

5.  Considere um novo vetor de pesos 
\[ 
W = 
\begin{bmatrix}
0.4 \\
0.4 \\
0.2 
\end{bmatrix} 
\]. Calcule a receita ponderada usando os pesos fornecidos e explique o que o resultado representa.


In [11]:
import numpy as np

# Definindo as matrizes de vendas (A), preços (B) e descontos (D)
A = np.array([[20, 30, 40],
              [15, 25, 35],
              [25, 35, 45]])

B = np.array([[5, 6, 7],
              [4, 5, 6],
              [6, 7, 8]])

D = np.array([[1, 1, 2],
              [0, 2, 1],
              [2, 1, 0]])

# 1. Calculando a matriz de receita total (C)
C = A * B
print("Matriz de Receita Total (C):")
print(C)
C = np.sum(C, axis=1)
print("\nReceita total para cada produto:", C)

# 2. Aplicando os descontos e calculando a matriz de receita final (E)
E = C - D
print("\nMatriz de Receita Final (E):")
print(E)

# 3. Verificando se as vendas do primeiro produto podem ser expressas como combinação linear
def verificar_dependencia_linear(vetores):
    # Converte a lista de vetores para uma matriz NumPy
    matriz = np.array(vetores)

    # Verifica se a matriz é quadrada
    if matriz.shape[0] == matriz.shape[1]:  # número de linhas igual ao número de colunas
        determinante = np.linalg.det(matriz)
        if determinante == 0:
            return True  # Dependente linearmente

    # Calcula o rank da matriz
    rank_matriz = np.linalg.matrix_rank(matriz)
    
    # O número de vetores é o número de linhas na matriz
    num_vetores = matriz.shape[0]  

    # Se o rank é menor que o número de vetores, eles são dependentes
    return rank_matriz < num_vetores

a = verificar_dependencia_linear(A)
if a:
    print("\nAs vendas do primeiro produto podem ser expressas como combinação linear das outras vendas.")
else:
    print("\nAs vendas do primeiro produto não podem ser expressas como combinação linear das outras vendas.")

# 4. Calculando a média das receitas totais para cada mês
mean_revenue = np.mean(E, axis=0)
print("\nMédia das receitas totais para cada mês:", mean_revenue)
print("Mês com maior média de receita:", np.argmax(mean_revenue) + 1)

# 5. Calculando a receita ponderada usando pesos
W = np.array([0.4, 0.4, 0.2])
weighted_revenue = np.dot(W, E)
print("\nReceita ponderada usando W:", weighted_revenue)


Matriz de Receita Total (C):
[[100 180 280]
 [ 60 125 210]
 [150 245 360]]

Receita total para cada produto: [560 395 755]

Matriz de Receita Final (E):
[[559 394 753]
 [560 393 754]
 [558 394 755]]

As vendas do primeiro produto podem ser expressas como combinação linear das outras vendas.

Média das receitas totais para cada mês: [559.         393.66666667 754.        ]
Mês com maior média de receita: 3

Receita ponderada usando W: [559.2 393.6 753.8]
