In [1]:
import numpy as np

In [34]:
num_paes = 1000

In [35]:
# Inventando paezinhos imaginários.

# Pesos: cerca de 50g, com desvio padrão de 3g.
pesos = 50 + 3*np.random.randn(num_paes, 1)

# Temperatura: cerca de 22 graus Celsius, com desvio padrão de 5 graus.
temps = 22 + 5*np.random.randn(num_paes, 1)

# Volume em ml: 3 ml por grama de massa, mais 4ml por grau acima de 22.
volume = 3*pesos + 4*(temps - 22) + 5*np.random.randn(num_paes, 1)

In [36]:
X = np.c_[pesos, temps]
y = volume

In [37]:
X.shape, y.shape

((1000, 2), (1000, 1))

In [38]:
# Vamos dividir em treino e teste.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [39]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

# Aqui é onde o modelo aprende.
model.fit(X_train, y_train)

LinearRegression()

In [40]:
model.intercept_, model.coef_

(array([-88.56642839]), array([[3.02442992, 3.97273861]]))

O modelo final é:

$$
\hat{y} = \overset{\theta_0}{-81.65} + \overset{\theta_1}{2.88} x_1 + \overset{\theta_2}{4.02} x_2
$$

In [41]:
y_pred = model.predict(X_test)

In [42]:
from sklearn.metrics import root_mean_squared_error

root_mean_squared_error(y_test, y_pred)

np.float64(4.869658056030683)

Agora suponha que o padeiro ficou louco, e resolveu duplicar a coluna de peso de pãozinho:

In [43]:
X = np.c_[pesos, pesos, temps]
y = volume

In [44]:
X[:5,:]

array([[47.12107601, 47.12107601, 22.86243556],
       [51.68075569, 51.68075569, 22.41804087],
       [46.13334579, 46.13334579, 23.08613549],
       [51.66907804, 51.66907804, 20.62257024],
       [54.24709253, 54.24709253, 18.72305532]])

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [46]:
model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [50]:
np.linalg.inv(X_train.T @ X_train) @ X_train.T @ y_train

LinAlgError: Singular matrix

In [52]:
from sklearn.linear_model import Ridge

model = Ridge(alpha=1)

model.fit(X_train, y_train)

Ridge(alpha=1)

In [53]:
model.coef_, model.intercept_

(array([[1.49164116, 1.49164116, 4.02155582]]), array([-87.49417063]))